import { SnippetString } from "vscode";
import PostfixHandler from "../../base/PostfixHandler";
import { EnablePostfixSuggestion } from "../../base/decorator/EnablePostfixSuggestion";
import { Target } from "../../base/decorator/Target";
import { Return } from "../../base/decorator/Return";

@EnablePostfixSuggestion({ language: "markdown", label: "codeblock" })
class CodeBlockPostfixHandler extends PostfixHandler {
    private static readonly LANGS = [
        "c",
        "abnf",
        "accesslog",
        "actionscript",
        "ada",
        "apache",
        "applescript",
        "arduino",
        "armasm",
        "asciidoc",
        "aspectj",
        "autohotkey",
        "autoit",
        "avrasm",
        "awk",
        "axapta",
        "bash",
        "basic",
        "bnf",
        "brainfuck",
        "cal",
        "capnproto",
        "ceylon",
        "clean",
        "clojure",
        "clojure-repl",
        "cmake",
        "coffeescript",
        "coq",
        "cos",
        "cpp",
        "crmsh",
        "crystal",
        "cs",
        "c#",
        "csharp",
        "csp",
        "css",
        "d",
        "dart",
        "delphi",
        "diff",
        "django",
        "dns",
        "dockerfile",
        "dos",
        "dsconfig",
        "dts",
        "dust",
        "ebnf",
        "elixir",
        "elm",
        "erb",
        "erlang",
        "erlang-repl",
        "excel",
        "fix",
        "flix",
        "fortran",
        "fsharp",
        "gams",
        "gauss",
        "gcode",
        "gherkin",
        "glsl",
        "go",
        "golang",
        "golo",
        "gradle",
        "groovy",
        "haml",
        "handlebars",
        "haskell",
        "haxe",
        "hsp",
        "htmlbars",
        "http",
        "hy",
        "inform7",
        "ini",
        "irpf90",
        "java",
        "javascript",
        "js",
        "json",
        "julia",
        "kotlin",
        "lasso",
        "ldif",
        "leaf",
        "less",
        "lisp",
        "livecodeserver",
        "livescript",
        "llvm",
        "lsl",
        "lua",
        "makefile",
        "markdown",
        "mathematica",
        "matlab",
        "maxima",
        "mel",
        "mercury",
        "mipsasm",
        "mizar",
        "mojolicious",
        "monkey",
        "moonscript",
        "n1ql",
        "nginx",
        "nimrod",
        "nix",
        "nsis",
        "objectivec",
        "ocaml",
        "openscad",
        "oxygene",
        "parser3",
        "perl",
        "pf",
        "php",
        "pony",
        "powershell",
        "processing",
        "profile",
        "prolog",
        "protobuf",
        "puppet",
        "purebasic",
        "py",
        "python",
        "q",
        "qml",
        "r",
        "rib",
        "roboconf",
        "rsl",
        "ruby",
        "ruleslanguage",
        "rust",
        "scala",
        "scheme",
        "scilab",
        "scss",
        "smali",
        "smalltalk",
        "sml",
        "sqf",
        "sql",
        "stan",
        "stata",
        "step21",
        "stylus",
        "subunit",
        "swift",
        "taggerscript",
        "tap",
        "tcl",
        "tex",
        "toml",
        "thrift",
        "tp",
        "twig",
        "ts",
        "typescript",
        "vala",
        "vbnet",
        "vbscript",
        "vbscript-html",
        "verilog",
        "vhdl",
        "vim",
        "x86asm",
        "xl",
        "xml",
        "xquery",
        "yml",
        "yaml",
        "zephir",
    ];
    private static readonly SET = new Set<String>(CodeBlockPostfixHandler.LANGS);

    @Target.Slice({ start: " " })
    @Return.Replace()
    handleLineText(replacement: string, data: {}) {
        // 如果 data["startIndex"] 原本 == -1
        if (data["startIndex"] === -1) {
            data["startIndex"] = data["firstNotWhiteSpaceIndex"];
        } else {
            data["startIndex"]++;
            replacement = replacement.substring(1);
        }
        if (CodeBlockPostfixHandler.SET.has(replacement)) {
            return new SnippetString("```" + replacement + "\n${0}\n```");
        }
        return null;
    }
}
